version: "3.3"
services:
    main:
        build: .
        image: jestrr/monitor:0.13.0
        entrypoint: ["pm2", "start", "/home/app/src/config/pm2.config.js", "--no-daemon"]
        volumes:
            - /etc/ssl/creds:/home/app/creds
            - /etc/serverkey:/home/app/serverkey
            - /etc/domain:/home/app/domain
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/local/bin/docker
            ## Remote
            - /root/.docker/config.json:/root/.docker/config.json
            - /root/repos:/home/app/repos
            ## Local/Dev
            # - $HOME/.docker/config.json:/root/.docker/config.json
            # - $HOME/code/temprepo:/home/app/repos
            # - ./src:/home/app/src
            # - ./server:/home/app/server
        extra_hosts:
            localmachine: "172.17.0.1"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                  - spread: node.labels.dc
        ports:
            # HOST:CONTAINER
            # Host WS Port:Container WS Port
            # - "172.17.0.1:4040:4000" # Swarm dev
            # - "172.17.0.1:4041:4001" # Swarm dev
            - "4040:4000"            # Prod
            - "4041:4001"            # Prod
        labels:
            com.consul.service: monitor
        environment:
            # Consul
            REGISTER_SERVICE: "true"
            # Server
            PUB_FILES: ./pub/
            BIN: ./server/bin/
            OUTPUT_FILES: ./server/output/
            USE_AUTH: "true"
