version: "3.5"
services:
    dev:
        build:
            context: .
            target: src
        image: jestrr/monitor:dev
        entrypoint: ["pm2-runtime", "server/pm2.config.js"]
        volumes:
            - /etc/ssl/creds:/home/app/creds
            - /etc/serverkey:/home/app/serverkey
            - /etc/domain:/home/app/domain
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/local/bin/docker

            - $HOME/.docker/config.json:/root/.docker/config.json
            - $HOME/code/temprepo:/home/app/repos
            - ./src:/home/app/src
            - ./server:/home/app/server
        extra_hosts:
            localmachine: "172.17.0.1"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                max_failure_ratio: 1
                order: start-first
            restart_policy:
                max_attempts: 3
                # condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az
        ports:
            # HOST:CONTAINER
            # Host WS Port:Container WS Port
            # - "172.17.0.1:4040:4000" # Swarm dev
            # - "172.17.0.1:4041:4001" # Swarm dev
            - "4040:4000"            # Prod
            - "4041:4001"            # Prod
        labels:
            com.consul.service: monitor
        environment:
            REGISTER_SERVICE:   "false"
            USE_AUTH:           "false"
            USE_CONSUL_DB:      "false"
