version: "3.5"
services:
    main:
        build:
            context: .
            target: prod
        image: jestrr/monitor:0.16.3
        networks:
            - proxy
        ports:
            - "4050:80"
        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
                failure_action: rollback
                max_failure_ratio: .3
                order: start-first
            restart_policy:
                max_attempts: 3
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
                preferences:
                    - spread: node.labels.dc
                    - spread: node.labels.az

networks:
    proxy:
        external: true
