version: "3"
services:
    main:
        build: .
        image: jestrr/monitor:0.6.0
        entrypoint: ["pm2", "start", "/home/app/src/config/pm2.config.js", "--no-daemon"]
        # volumes:
        #     - ./src:/home/app/src
        #     - ./server:/home/app/server
            # - ./pub:/home/app/pub
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                max_attempts: 3
                condition: on-failure
        ports:
            # HOST:CONTAINER
            - "4040:4000"
            # Host WS Port:Container WS Port
            - "4041:4001"

        environment:
            PUB_FILES: ./pub/
            BIN: ./server/bin/
            OUTPUT_FILES: ./server/output/

            # 172.17.0.1
            CONSUL_LEADER: 172.17.0.1 # Change

            # Consul
            SERVICE_NAME: monitor
            SERVICE_PORT: 4040
            REGISTER_SERVICE: "true"
            IMAGE_VER: 0.6.0
